Swerve changes
ChainLynxRobotics/2023_Season pull request #7
Opened 2023-03-03 21:33 UTC by Irishumanoid

Competition code

2023-03-10 20:06 UTC, garrettwitowski requested changes
Overall pretty good. To get approval, please:
1. Remove dead/unused code
2. Clean up the ElevatorSubsystem
3. Create a backlog item to track the other comments/nits

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/ArmTest.java
> +package frc.robot.Commands;
Please remove this file

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/ElevatorCommand.java
> +package frc.robot.Commands;
Can we stub out this file (leave the methods empty)? I'd rather us start it from a blank slate.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/ElevatorPIDCommand.java
> +package frc.robot.Commands;
Let's delete this file

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/IntakeCommand.java
> +    //arm down, turn on intake
nit: can we adjust this comment?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/IntakeCommand.java
> +        System.out.println("IntakeCommand::execute");
nit: we should probably remove this debug statement, right?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/ReleaseCommand.java
> +    //arm down, turn on intake
nit: adjust this comment

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/ScoreGamePieceCommand.java
> +package frc.robot.Commands;
Can we stub this out please?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/SimpleDriveCommand.java
> +            MathUtil.applyDeadband(-multiplier*controller.getLeftY(), 0.06),
nit: let's use the values from Constants.java here instead of the hard-coded values

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Commands/ToStartConfigCommand.java
> +public class ToStartConfigCommand extends CommandBase {
Do we need this? If so, let's stub it out.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Constants.java
> +    public static final int kRearLeftDrivingCanId = 4;
Just curious, when did these change?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Constants.java
> +  public static final double CAMERA_HEIGHT = 0.15;
These aren't the final values right? Let's mark them with TODO comments. Also, it'd be nice if we could determine the units for these (i.e., meters, inches, furlongs, etc.)

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Constants.java
> +  //to do: change to actual ports
These ports are correct, right? Let's remove this comment :)

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Constants.java
> +  public static final double ELEVATOR_kS = 0.2;
Do we need these?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Constants.java
> +  public static final int SOLENOID_forward1 = 0;
What are these for?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Constants.java
> +  public enum ScoringLocation {
nit: enum values should be on separate lines

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/GenericPID/Approximations/ApproximateDerivative.java
> +package frc.robot.GenericPID.Approximations;
Delete this please.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/GenericPID/Approximations/ApproximateIntegral.java
> +package frc.robot.GenericPID.Approximations;
Delete this please

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/GenericPID/Approximations/DoubleFunction.java
> +package frc.robot.GenericPID.Approximations;
Delete

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/GenericPID/Approximations/Zero.java
> +package frc.robot.GenericPID.Approximations;
Delete

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/GenericPID/GenericPID.java
> +package frc.robot.GenericPID;
Delete

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/GenericPID/PIDConfig.java
> +package frc.robot.GenericPID;
Delete

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/GenericPID/Testing/Motor.java
> +package frc.robot.GenericPID.Testing;
Delete

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Logger/Logger.java
> +public class Logger {
What is the purpose of this class?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Logger/LoggerEntryBase.java
> +package frc.robot.Logger;
Is this in use?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Logger/LoggerRawEntryBase.java
> +package frc.robot.Logger;
In use?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> + //trajectory -- command:
nit: what is this comment for?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> +      autoChooser.addOption("Simple Trajectory", AutoModes.SIMPLE_TRAJECTORY);
Can we remove unused autos for now and stub them out?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> +      //simpleTrajectoryCommand(container, initDriveToScore())
Remove dead code please

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> +    //test
Tag with TODO please

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> +    //test
Tag with TODO

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> +    private Trajectory getOnChargeStation(StartPos pos) {
TODO

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> +    private Trajectory driveToStagedGamePiece(StartPos pos) {
TODO

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> +  private enum AutoModes {
nit: enum entries should be on different lines

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/AutoUtils.java
> +    LEFT_CS, MID_CS, RIGHT_CS
nit: different lines

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/PathPlanningCode/GenerateTrajectoryFromFile.java
> +public class GenerateTrajectoryFromFile {
What does this do and does it work?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/RobotContainer.java
> +    //new JoystickButton(m_driverController, 2).whileTrue(new InstantCommand(() -> m_intake.intakeGamePiece(intakeSpeedMultiplier), m_intake));
Remove dead code

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/RobotContainer.java
> +    new Trigger(() -> m_operatorController.getRawButton(9))
nit: add some comments

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/RobotContainer.java
> +  public boolean triggerPressed() {
There's other ways of doing this right? This seems a bit odd.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/RobotTest.java
> +import edu.wpi.first.wpilibj.DoubleSolenoid;
Please delete this class -- it shouldn't be used.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/ArmSubsystem.java
> +    public void turnOff() {
Why did we add this?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/DriveSubsystem.java
> +import edu.wpi.first.wpilibj.ADIS16470_IMU;
Is this in use?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/DriveSubsystem.java
> +  //start of some team drive code
Delete this comment -- it's not meaningful

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/DriveSubsystem.java
> +    //slew rate fetched code
delete this comment -- it's not meaningful

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/DriveSubsystem.java
> +    //end of fetched code
Delete

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/DriveSubsystem.java
> +  /*@Override
If we think this is useful for diagnostics (it could be) then let's uncomment it. Otherwise, let's delete it.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/ElevatorSubsystem.java
> +//to do: error handling for if pid controllers get misaligned
nit: TODO (instead of "to do")

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/ElevatorSubsystem.java
> +      elevatorMotor1 = new CANSparkMax(Constants.ELEVATOR_MOTOR_ID_MASTER, MotorType.kBrushless);
Let's clean this up before we merge. Remove all unused variables, constants, etc.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/ElevatorSubsystem.java
> +     // input = MathUtil.clamp(SmartDashboard.getNumber("elevator motor power",0), -1, 1);
Dead code

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/ElevatorSubsystem.java
> +      System.out.println("joystick axis 1 at " + input);
If we think this is useful for future diagnostics let's put it on SmartDashboard, otherwise we should remove it.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/ElevatorSubsystem.java
> +    public List<CANSparkMax> getElevatorMotors() {
Do we need this?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/ElevatorTrapezoidalSubsystem.java
> +package frc.robot.Subsystems;
Delete this class please.

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/VisionSubsystem.java
> +        camera = new PhotonCamera("lol");
nit: at some point we should re-name this

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/VisionSubsystem.java
> +            add(createTag(1, 7.05, 0.995, 0.665, 180));
What are these for?

2023-03-10 20:06 UTC, garrettwitowski commented on src/main/java/frc/robot/Subsystems/VisionSubsystem.java
> +        for (PhotonTrackedTarget i : targets) {
nit: "i" isn't a particularly descriptive loop variable since we're using a for-each loop ("enhanced for loop") -- I'd suggest something more like "target"

2023-03-10 21:10 UTC, Irishumanoid commented on src/main/java/frc/robot/Constants.java
> +    public static final int kRearLeftDrivingCanId = 4;
when we switched to the competition chassis

2023-03-10 21:10 UTC, Irishumanoid commented on src/main/java/frc/robot/Constants.java
> +  public static final double CAMERA_HEIGHT = 0.15;
they're in meters

2023-03-10 21:12 UTC, Irishumanoid commented on src/main/java/frc/robot/Constants.java
> +  public static final double ELEVATOR_kS = 0.2;
once we implement the trapezoidal profile

2023-03-10 21:12 UTC, Irishumanoid commented on src/main/java/frc/robot/Constants.java
> +  public static final int SOLENOID_forward1 = 0;
for arm

2023-03-10 21:28 UTC, Irishumanoid commented on src/main/java/frc/robot/Subsystems/VisionSubsystem.java
> +            add(createTag(1, 7.05, 0.995, 0.665, 180));
adding april tag positions manually

2023-03-10 22:34 UTC, Irishumanoid commented on src/main/java/frc/robot/RobotContainer.java
> +  public boolean triggerPressed() {
yes but it works for now and I don't want to review this pr forever

2023-03-10 22:38 UTC, Irishumanoid reviewed
made most requested edits

2023-03-11 00:34 UTC, garrettwitowski approved these changes

2023-03-11 00:35 UTC, merged